runtime: custom
# vm: true
env: flex
skip_files:
  - ^(target|bench|example).*$

# default_expiration: "10m"

handlers:
  - url: /badge
    expiration: 1d
    static_dir: /badge

  - url: /npm
    expiration: 1d
    static_dir: /npm

  - url: /github
    expiration: 1d
    static_dir: /github

  - url: /crates
    expiration: 1d
    static_dir: /crates

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5