[package]
name = "merit"
version = "0.1.0"
authors = ["Suntharesan Mohan <suntharesan.mohan@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "merit"

[dependencies]
cssparser = "0.25"
hashbrown = "0.6"
lazy_static = "1.4"
maud = "0.21"
rusttype = "0.8"
scraper = "0.11"
unicode-normalization = "0.1"

clap = "2.33"
structopt = "0.3"

[workspace]
members = [
  "merit-api",
  "humanize"
]

[[bin]]
name = "merit"
