[package]
name = "badge-r-us"
version = "0.1.0"
authors = ["Suntharesan Mohan <suntharesan.mohan@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
badge-maker = { version = "0", path = "badge-maker" }
clap = "2.33"
structopt = "0.2"

[workspace]
members = [
  "badge-maker"
]
