[package]
name = "merit"
version = "0.1.1"
description = "Fast badge generator for any purpose"
license = "MIT"
authors = ["Suntharesan Mohan <suntharesan.mohan@gmail.com>"]
edition = "2018"
readme = "Readme.md"
repository = "https://github.com/msuntharesan/merit"
publish = true

[lib]
name = "merit"

[[bin]]
name = "merit"

[dependencies]
cssparser = "0.27"
clap = "2.33"
derive_builder = "0.9"
hashbrown = "0.7"
lazy_static = "1.4"
maud = "0.21"
rusttype = "0.8"
scraper = "0.11"
structopt = "0.3"
unicode-normalization = "0.1"

[workspace]
members = [
  "humanize",
  "merit-api",
]

[profile.release]
opt-level = 'z'  # Optimize for size.